---
title: "Haar-basis"
author: "Chang Shen (cs2628)"
date: "9/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r pressure, echo=TRUE}
haarEncode<-function(y, fidelity=.9, max.terms=100){
  # "basis" is a vector containing the indices of the
  # haar basis vectors that we want to save, ordered by importance.
  # "coeffs" is a vector of the coefficients of y with
  # respect to those basis vectors.
  # return a list with elment basis and coeffs
  n = 0
  fid = 0
  z <- t(B)%*%y
  order <- order(abs(z), decreasing=TRUE)
  appr <- rep(0, length(y))
  basis <-NULL
  ceoffs <- NULL
  i = 1
  s <- sum(y^2)
  while((i <= max.terms) && (fid < fidelity)) {
    appr <- appr + z[order[i]] * B[, order[i]]
    fid <- 1-sum((y-appr)^2/s)
    #print(cbind(i,fid)) #use to debug
    basis = cbind(basis,order[i])
    ceoffs = cbind(ceoffs,z[order[i]])
    i = i+1
  }
  return(list(basis_ = as.vector(basis),coeffs_ =  as.vector(ceoffs)))
}

#assume we know extactly dimension(1024) and have calculate the basis as B
haarDecode<-function(x,y) {
  order = x$basis_
  appr<- rep(0, n)
  for(i in 1:length(order)){
    appr<-appr + x$coeffs_[i]* B[, order[i]]
  }
  return(appr)
}

if(!"wmtsa"%in%installed.packages()){install.packages(wmtsa)}
library(wmtsa)
n <- 1024
dax <- EuStockMarkets[1:n, 1]
dax <- dax-mean(dax)
B <- wavDWTMatrix(wavelet='haar', J=log2(n))

x <- haarEncode(dax,0.9,100)
print(paste("the compression in this algorithm",as.character(length(x$basis_)/n)))# how much compression
appr <- haarDecode(x,dax)

fidelity <- 1-sum((dax-appr)^2/sum(dax^2))
plot(dax, type="l", main=paste("DAX and approximation, fidelity =", signif(fidelity, 3)))
lines(appr, col=2)
```

