---
title: "PCCOMPRESS_HW2"
author: "ChangShen"
date: "9/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=TRUE}
library(pixmap)

setwd("//Users//dianshen//Library//Mobile Documents//com~apple~CloudDocs//19Fall//LinearModel//Homework//faces")

flip <- function(M) {
  M <- M[nrow(M):1, ]
  return(t(M))
}

faces <- list()

n <- 15
for(i in 1:n) {
  facematrix <- flip(getChannels(read.pnm(file=paste0(i, ".pgm"), cellres=1)))
  faces[[i]] <- facematrix
}


PCcompress <- function(matrixList, fidelity=.9) {
  # Takes a list of matrices, all having the same dimensions,
  # unwinds them into vectors then saves just enough principal
  # components to achieve fidelity of .9.
  # Unwind the matrices into vectors, then stack these
  # vectors together into a matrix called "M"
  
  #d - dimension of the matrices index of the list.
  #vec.length - the length of the unwind vector
  #n - the number of the matrices in the list
  #face.mat - orignal nrows of the unwind vectors(wait for centering)
  #M - centering face.mat
  #approx - approximating matrices data
  
  #initialization
  d <- dim(matrixList[[1]])
  n <- length(matrixList)
  vec.length <- d[1]*d[2]
  faces.mat <- matrix(NA, nrow=n, ncol=vec.length)
  coefs <-NULL
  
  for(i in 1:n) {
    faces.mat[i, ] <- as.vector(faces[[i]])
  }
  
  m <- apply(faces.mat, 2, mean)
  M <- sweep(faces.mat, 2, m)
  
  s <- svd(M/sqrt(n))
  
  fid <- cumsum(s$d^2)/sum(s$d^2)
  fid.pc <- min(which(fid>fidelity))
  
  PCs <- s$v[, 1:fid.pc]
  
  for(j in 1:fid.pc) {
  # calculate its coefficients for the data vectors
  coefs <- cbind(coefs, M %*% s$v[, j]) 
  coefficient <- M %*% s$v[, j]
}
  
  
  # Create the following objects to return:
  # - "m" should be the average vector. ok
  # - "PCs" should be a matrix containing as its columns
  #    the PC vectors that you want to keep.
  # - "coefs" should be a matrix of the coefficients of these PCs
  #    with respect to the n data vectors. Row j of coefs should
  #    have all the coefficients for obervation j. ok
  #    observation <- every pic 
  
  
  return(list(numrows=nrow(matrixList[[1]]), m=m, PCs=PCs, coefs=coefs))
}



PCuncompress <- function(compressed) {
  # Takes the output of pccompress and converts it to a list
  # containing the approximations of the original matrices.
  
  n <- nrow(compressed$coefs)
  PCs <- compressed$PCs
  coefs <-compressed$coefs
  apprs <- matrix(rep(compressed$m, n), byrow=TRUE, nrow=n)

  for(j in 1:ncol(coefs)){
      for(i in 1:n) {
        apprs[i, ] <- apprs[i, ] + coefs[i,j]*PCs[, j]
    }
  }

  
  # ALL YOU NEED TO DO HERE is create a matrix called apprs
  # with each row corresponding to an unwound approximation.
  # Access the principal components using compressed$PCs
  # and the coefficients using compressed$coefs.
  # The following loop coverts appr into a list of matrices
  # which will be returned by the function.
  matrixList <- list()
  for(i in 1:n) {
    matrixList[[i]] <- matrix(apprs[i, ], nrow=compressed$numrows)
  }
  
  return(matrixList)
}


# Run your functions on the faces data to make sure they work:

x <- PCcompress(faces)
apprs <- PCuncompress(x)

par(mfrow=c(3, 5), mar=c(0, 0, 0, 0), oma=c(0, 0, 4, 0))
for(i in 1:n) {
  image(apprs[[i]], yaxt="n", xaxt="n")
}
mtext("approximations", side=3, line=1, cex=2, outer=TRUE)
#dev.off()

```
